# Generated by Django 5.1.4 on 2025-01-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_account', '0003_alter_surfspot_location_alter_surfspot_title_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='surfspot',
            name='category',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Advanced', 'Advanced'), ('For Everyone', 'For Everyone')], default='For Everyone', max_length=20),
        ),
    ]
